name: Bridgecrew
on:
  pull_request:
  push:
    branches:
      - master    
jobs:
  scan:
    runs-on: ubuntu-latest 
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
     
    steps:
    - uses: actions/checkout@v2
    
    - name: Run Prisma Cloud
      id: workshop-codesecurity
      uses: bridgecrewio/bridgecrew-action@master
      env:
        PRISMA_API_URL: https://app2.prismacloud.io
      with:
        api-key: ${{ secrets.BC_API_KEY }}
        directory: terraform/
        #soft_fail: true
